global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'flash-sale-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'auth-app-1:3000'
          - 'auth-app-2:3000'
          - 'auth-app-3:3000'
          - 'auth-app-4:3000'
          - 'auth-app-5:3000'
          - 'auth-app-6:3000'
        labels:
          group: 'flash-sale-cluster'
