export const HTTP_REQUESTS_TOTAL = 'HTTP_REQUESTS_TOTAL';
export const HTTP_REQUEST_DURATION_SECONDS = 'HTTP_REQUEST_DURATION_SECONDS';
export const FLASH_SALE_ORDERS_TOTAL = 'FLASH_SALE_ORDERS_TOTAL';
export const FLASH_SALE_QUEUE_JOBS_TOTAL = 'FLASH_SALE_QUEUE_JOBS_TOTAL';
export const FLASH_SALE_STOCK_GAUGE = 'FLASH_SALE_STOCK_GAUGE';
